  File "01-2.Statistics_SAVE_images_using_DF_Y.py", line 7
SyntaxError: Non-ASCII character '\xec' in file 01-2.Statistics_SAVE_images_using_DF_Y.py on line 7, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
